### ISSUE TITLE
How this relates to Modules\vis\visualisations\graph

### ISSUE THREAD

**Issue by chaveiro** [emoncms/graph#3]
Is this a replacement for \Modules\vis\visualisations\graph ?
Visualization graphs are modular also with the bonus that they are usable inside a dashboard, this module alone cant.
What is the idea?

**Comment by TrystanLea** [comment]
Sorry @chaveiro it was easier to keep the code separate in order to develop something new in this case. Both vis and graph are still complimentary at the moment, graph does replace visualisations\graph. Ultimately the graph module can replace: multigraph, rawdata and bargraph. But the idea of replacing stalled for now, graph got to a useful level and with everything else to do, that's the point this got too.
