### ISSUE TITLE
Errors when zooming out too far on some graphs 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/graph#70]
`Notice: Undefined offset: 1 in /var/www/emoncms/Modules/feed/feed_model.php on line 607
[{"feedid":"1","data":{"success":false,"message":"request end time before start time"}}], 
Notice: Undefined offset: 0 in /var/www/emoncms/Modules/feed/feed_model.php on line 607`

![Selection_113](https://user-images.githubusercontent.com/758844/54774158-fd032c80-4c02-11e9-8a25-d84aa8711aec.jpg)

**Comment by emrysr** [comment]
I see a different message:
![delwedd](https://user-images.githubusercontent.com/1466013/55077067-cf006b00-508e-11e9-96be-12b8ba22493b.png)

Would it make a difference what type of feed is used? or how far back your feed goes.
@glynhudson I'll msg you privately for a copy of your feeds so that I can test it here.

**Comment by glynhudson** [comment]
Just tested. I get the same message for all my feeds. You already have all my feeds in the backup zip I shared with you. My power feed is ID 1 and Solar PV is ID 192

**Comment by emrysr** [comment]
the feed module api returns an error message not in `json` format. I'll try to check for that case within  `graph.js` however another issue will need to be raised in the `emoncms` to identify and fix the issue so that it returns an error message in `json` format.
